### ISSUE TITLE
onnxruntime error !!!

### ISSUE THREAD

**Issue by zoey9628** [oooooha/loftr2onnx#2]
Can you share your version of onnx and onnxruntime? After I convert the model into onnx, have onnxruntime. InferenceSession (model_path) error.
![Uploading image.png…]()

This is my onnx & onnxruntime version
![Uploading image.png…]()

**Comment by zoey9628** [comment]
There is something wrong with the picture uploaded just now, I will send it again, as follows
error message:
![8e49b16e864d9b8693b7af129ed28c50](https://github.com/oooooha/loftr2onnx/assets/120021259/5abb6066-8f65-4858-9daf-046b79eca3fd)

 my onnx & onnxruntime version
![image](https://github.com/oooooha/loftr2onnx/assets/120021259/beb64518-4075-47a0-af59-491b72353c95)


Looking forward to your reply very much~ ：）

**Comment by zoey9628** [comment]
fixed! in coarse_matching.py  : )
![image](https://github.com/oooooha/loftr2onnx/assets/120021259/6ff9c1ea-fb07-4c8b-8935-93b269ac3aad)

**Comment by bromotdi** [comment]
Hi! Can you please share generated .onnx file?

**Comment by zoey9628** [comment]
> Hi! Can you please share generated .onnx file?

sorry，I have deleted the .onnx file.
